### ISSUE TITLE
Client Side - Adding email feature

### ISSUE THREAD

**Issue by hadiab** [mohamadir/15-minutes#15]
Todo: 
- adding email feature, after the client submit the report form he will receive an email from 15 minutes organization
- change the email message content, that the 15-min-client will provide

**Comment by hosenja** [comment]
i will done this :+1:

**Comment by osyejda** [comment]
i think that should be a short message

**Comment by hosenja** [comment]
its my game

**Comment by hadiab** [comment]
when you done change the label to done and close it

**Comment by hosenja** [comment]
osed  i will check the ionic and all the issiue ,...

**Comment by mohamadir** [comment]
بيعوا بيظ
