### ISSUE TITLE
iteration 3 - Server side

### ISSUE THREAD

**Issue by hadiab** [mohamadir/15-minutes#26]
## iteration 3 - Server side

[iteration 3 ](https://github.com/mohamadir/15-minutes/wiki/SS)

**Comment by hadiab** [comment]
@ItamarShDev

**Comment by ItamarShDev** [comment]
please WRITE the goals as a list
please refer to testing methods, and next iteration plans it there are
also, write a summary of this iteration

**Comment by hadiab** [comment]
@ItamarShDev  Done.

**Comment by ItamarShDev** [comment]
:+1:
