### ISSUE TITLE
srs - fix 

### ISSUE THREAD

**Issue by mohamadir** [mohamadir/15-minutes#3]

**Comment by mohamadir** [comment]
## סקר הלקוח 

ותק: 15 דקות 15minutes.co.il@gmail.com, Oded Gvaram odedgvr@gmail.com
נושא: בעניין: מסמך דרישות - המכללה להנדסה - אפליקצייה של הארגון
נראה רציני מאוד :smile:
כמה נקודות להבהרה:
חסר בתרשימי הזרימה ובכלל בהצגה של הדברים - מה קורה עם התלונה, לאן היא הולכת, מה קורה אחרי שממלאים את הפרטים - לאן זה מגיע , איך זה מגיע וכו'..
לגבי אפשרות הצילום - לדעתי זה צריך להיות ברור מאוד ופשוט מאוד, לא ממש הבנתי איך זה משתלב כרגע.
נושא הרישום לאפליקציה - כדאי לקבל הבהרות עד כמה זה ישפיע על סירבול ואיך יהיה הכי פחות מרתיע שאפשר והכי קצר שאפשר..
רעיון ?-נראה לי שכדאי שתישמר אופציה עתידית לשילוב את האפליקציה במוביט או מישהו בסדר גודל הזה , כמובן שישלמו לנו על זה.. (או שהגזמתי?...)
צריך לחשוב איתם בעזרת דפנה על רמת הפירוט המינימלית הנדרשת בפרטי התלונה שממלאים. דפנה יש לך הערות על זה?
וכמובן שהאתגר האמיתי הוא בהפצה של זה והגעה לחשיפה גדולה...
סה"כ נראה סבבה (אם כי אני לא מבין גדול באפליקציות...)

**Comment by mohamadir** [comment]
עדכנתי את הקובץ לפי הסקר

**Comment by mohamadir** [comment]
@ItamarShDev  
אם תוכל לבדוק את זה שוב בבקשה תודה

**Comment by mohamadir** [comment]
העדכון:
1. שינוי משתמש ל נוסע 
2. הבהרת עניין התלונה על ידי יצירת תרישם זרימה

**Comment by mohamadir** [comment]
https://docs.google.com/document/d/1aWuRR5wPazvdNnR78T3rhJyu5o6wizhHf5sQ3-4jaDs/edit

**Comment by ItamarShDev** [comment]
fixed
