### ISSUE TITLE
mvp

### ISSUE THREAD

**Issue by mohamadir** [mohamadir/15-minutes#7]

**Comment by mohamadir** [comment]
[mvp](https://github.com/mohamadir/15-minutes/wiki/MVP)

**Comment by mohamadir** [comment]
@ItamarShDev

**Comment by mohamadir** [comment]
we added the test units to the mvp in wiki , can u  kindly check  that?
thanx

**Comment by robi-y** [comment]
Don't forget to assign Itamar...

**Comment by mohamadir** [comment]
@ItamarShDev 
now u can check and  fix the grades, 
-added unit tests
- added code review
